/*========================================================================================================================
	Magnitude Analysis
========================================================================================================================
	Script Purpose:
		1.) quantify data and group by specific dimensions.
		2.) Understanding data distribution across categories
	SQL functioins used:
		1.) Aggregate functions: SUM(), COUNT(), AVG(), 
		2.) GROUP BY, ORDER BY

========================================================================================================================
*/

-- Find total Number of customers by country
SELECT 
	country,
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales AS sa
LEFT JOIN gold.dim_customers AS cu
ON sa.customer_key = cu.customer_key
GROUP BY country
ORDER BY 2 DESC;

--Find total customers by gender
SELECT
	gender,
	COUNT(DISTINCT customer_number)
FROM gold.fact_sales AS sa
LEFT JOIN gold.dim_customers AS cu
ON sa.customer_key = cu.customer_key
GROUP BY gender
ORDER BY 2 DESC;

--Find total products by category
SELECT
	category,
	COUNT(product_key) AS Nr_products
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC;

--What is the average cost in each category
SELECT
	category,
	AVG(cost) AS Avg_cost
FROM gold.dim_products 
GROUP BY category
ORDER BY 2 DESC;

--What is the total revenue generated for each category?
SELECT
	category,
	SUM(sales_amount) AS Total_revenue
FROM gold.fact_sales AS sa
LEFT JOIN gold.dim_products pr
ON sa.product_key = pr.product_key
GROUP BY category
ORDER BY 2 DESC;

--Find total revenue generated by each customer.
SELECT
	TOP(10)
	cu.first_name,
	cu.last_name,
	SUM(sales_amount) AS Total_revenue
FROM gold.fact_sales AS sa
LEFT JOIN gold.dim_customers AS cu
ON sa.customer_key = cu.customer_key
GROUP BY cu.first_name,cu.last_name
ORDER BY 3 DESC;

--What is the distribution of items sold across countries?
SELECT 
	country,
	SUM(quantity) AS Nr_items_sold
FROM gold.fact_sales AS sa
LEFT JOIN gold.dim_customers AS cu
ON sa.customer_key = cu.customer_key
GROUP BY country
ORDER BY 2 DESC;
